### ISSUE TITLE
sql timestamps

### ISSUE THREAD

**Issue by srwang** [srwang/forum_project#1]
Hey Jason,

I wanted to include both a "Posted at" and "Edited at" field for edited comments.  I was wondering if it was possible to get two timestamps- one for created time and one for updated time.  Right now I have this and they're both the same (lol):

CREATE TABLE comments (
    id INTEGER PRIMARY KEY autoincrement,
    body TEXT,
    like_count INTEGER,
    topic_id INTEGER,
    user_id INTEGER, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (user_id) REFERENCES users(id)
);

thank you!!

**Comment by Jingo88** [comment]
Try this and lmk if you get it working. You'll have to add this in your serverside code, not db schema

http://stackoverflow.com/questions/5956215/how-can-i-store-the-current-timestamp-in-sqlite-as-ticks
